services:
  backend:
    build: ./bonaso_data_server
    command: gunicorn bonaso_data_server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./bonaso_data_server:/app
    env_file:
      - ./bonaso_data_server/.env
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:17.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

  nginx:
    build: ./bonaso_data_web
    ports:
      - "80:80"
    volumes:
      - ./bonaso_data_server/static:/static:ro
      - ./bonaso_data_server/media:/media:ro
    depends_on:
      - backend

volumes:
  postgres_data: